# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Huginn for Newsrooms
email: albert.sun@nytimes.com
description: > # this means to ignore newlines until "baseurl:"
  How newsrooms can use Huginn.
baseurl: "/huginn-newsroom-scenarios" # the subpath of your site, e.g. /blog
url: "http://albertsun.github.io" # the base hostname & protocol for your site


# Build settings
markdown: kramdown

github: [metadata]
kramdown:
  input: GFM
  hard_wrap: false
gems:
  - jekyll-paginate
